// server/git-manager.js – Git operations for generated projects
import { runInSandbox } from "./docker-runner.js";
import { getCredential } from "./credential-manager.js";
import logger from "./logger.js";
import axios from "axios";

/**
 * Initialize a Git repo, add all files, and commit.
 * @param {string} sourceDir  Absolute path to the project source directory.
 * @param {string} commitMsg  Commit message.
 */
export async function initAndCommit(sourceDir, commitMsg = "Initial AI-generated commit") {
  logger.info("git-manager: initializing repo", { sourceDir });

  const commands = [
    "git config --global --add safe.directory /app",
    "git init",
    "git add -A",
    `git commit -m "${commitMsg.replace(/"/g, '\\"')}"`,
  ].join(" && ");

  const result = await runInSandbox({
    command: commands,
    workDir: sourceDir,
    envVars: {
      GIT_AUTHOR_NAME: "ChatForge",
      GIT_AUTHOR_EMAIL: "chatforge@automated.ai",
      GIT_COMMITTER_NAME: "ChatForge",
      GIT_COMMITTER_EMAIL: "chatforge@automated.ai",
    },
  });

  if (result.exitCode !== 0) {
    logger.error("git-manager: git init failed", { stderr: result.stderr });
    throw new Error(`Git init failed: ${result.stderr}`);
  }

  logger.info("git-manager: repo initialized and committed");
  return result;
}

/**
 * Create a GitHub repository via the API and push code.
 * @param {string} sourceDir  Absolute path to the source directory.
 * @param {string} repoName   Desired GitHub repository name.
 * @param {boolean} isPrivate  Whether the repo should be private.
 * @returns {Promise<string>}  The GitHub repo URL.
 */
export async function createAndPush(sourceDir, repoName, isPrivate = true) {
  const token = getCredential("GITHUB_TOKEN");
  if (!token) {
    throw new Error("GITHUB_TOKEN credential is required. Send: CRED GITHUB_TOKEN=your_token");
  }

  // Sanitize repo name
  const safeName = repoName.replace(/[^a-zA-Z0-9_.-]/g, "-");

  logger.info("git-manager: creating GitHub repo", { name: safeName });

  // Get authenticated user first (needed for repo lookup and URL construction)
  const userRes = await axios.get("https://api.github.com/user", {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    timeout: 15_000,
  });
  const owner = userRes.data.login;

  let repoUrl;

  // Try to create repo; if it already exists (422), fetch the existing one
  try {
    const response = await axios.post(
      "https://api.github.com/user/repos",
      {
        name: safeName,
        private: isPrivate,
        auto_init: false,
        description: "Generated by ChatForge AI",
      },
      {
        headers: {
          Authorization: `Bearer ${token}`,
          Accept: "application/vnd.github+json",
          "X-GitHub-Api-Version": "2022-11-28",
        },
        timeout: 30_000,
      }
    );
    repoUrl = response.data.clone_url;
  } catch (err) {
    if (err.response?.status === 422) {
      // Repo already exists – use the existing one
      logger.info("git-manager: repo already exists, reusing", { owner, name: safeName });
      repoUrl = `https://github.com/${owner}/${safeName}.git`;
    } else {
      throw err;
    }
  }

  const pushUrl = repoUrl.replace("https://", `https://x-access-token:${token}@`);

  // Initialize git repo if not already done, then set remote and push
  const commands = [
    "git config --global --add safe.directory /app",
    "git init",
    "git add -A",
    'git diff --cached --quiet || git commit -m "ChatForge AI-generated commit"',
    `git remote remove origin 2>/dev/null; git remote add origin "${pushUrl}"`,
    "git branch -M main",
    "git push -u origin main --force",
  ].join(" && ");

  const result = await runInSandbox({
    command: commands,
    workDir: sourceDir,
    envVars: {
      GIT_AUTHOR_NAME: "ChatForge",
      GIT_AUTHOR_EMAIL: "chatforge@automated.ai",
      GIT_COMMITTER_NAME: "ChatForge",
      GIT_COMMITTER_EMAIL: "chatforge@automated.ai",
    },
  });

  if (result.exitCode !== 0) {
    logger.error("git-manager: push failed", { stderr: result.stderr });
    throw new Error(`Git push failed: ${result.stderr}`);
  }

  logger.info("git-manager: pushed to GitHub", { url: repoUrl });
  return repoUrl;
}

/**
 * Delete a GitHub repository.
 * @param {string} repoName  Repository name to delete.
 * @returns {Promise<void>}
 */
export async function deleteRepo(repoName) {
  const token = getCredential("GITHUB_TOKEN");
  if (!token) {
    throw new Error("GITHUB_TOKEN credential is required. Send: CRED GITHUB_TOKEN=your_token");
  }

  const safeName = repoName.replace(/[^a-zA-Z0-9_.-]/g, "-");

  // Get authenticated user
  const userRes = await axios.get("https://api.github.com/user", {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    timeout: 15_000,
  });
  const owner = userRes.data.login;

  logger.info("git-manager: deleting GitHub repo", { owner, repo: safeName });

  await axios.delete(`https://api.github.com/repos/${owner}/${safeName}`, {
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: "application/vnd.github+json",
      "X-GitHub-Api-Version": "2022-11-28",
    },
    timeout: 15_000,
  });

  logger.info("GitHub repository deleted", { repo: safeName });
}
